"""create assets table

Revision ID: a37be809d87d
Revises: a4e638fe58bd
Create Date: 2026-08-02 16:18:38.520422

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a37be809d87d"
down_revision: str | Sequence[str] | None = "a4e638fe58bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=True),
        sa.Column(
            "asset_type",
            sa.Enum(
                "server",
                "workstation",
                "laptop",
                "virtual_machine",
                "container",
                "kubernetes_node",
                "network_device",
                "firewall",
                "router",
                "switch",
                "cloud_instance",
                "database",
                "storage",
                "domain",
                "website",
                "application",
                "other",
                name="asset_type",
            ),
            server_default="other",
            nullable=False,
        ),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("mac_address", sa.String(length=17), nullable=True),
        sa.Column("operating_system", sa.String(length=200), nullable=True),
        sa.Column("operating_system_version", sa.String(length=100), nullable=True),
        sa.Column(
            "environment",
            sa.Enum(
                "production",
                "staging",
                "development",
                "test",
                "sandbox",
                "unknown",
                name="asset_environment",
            ),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column(
            "criticality",
            sa.Enum("critical", "high", "medium", "low", name="asset_criticality"),
            server_default="medium",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("active", "inactive", "decommissioned", "unknown", name="asset_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("owner", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "tags", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "discovery_source",
            sa.Enum(
                "manual",
                "api",
                "agent",
                "network_scan",
                "cloud_connector",
                "import",
                "other",
                name="asset_discovery_source",
            ),
            server_default="manual",
            nullable=False,
        ),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_assets_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
        sa.UniqueConstraint("organization_id", "hostname", name="uq_assets_organization_hostname"),
    )
    op.create_index(op.f("ix_assets_ip_address"), "assets", ["ip_address"], unique=False)
    op.create_index(op.f("ix_assets_organization_id"), "assets", ["organization_id"], unique=False)
    op.create_index(
        "ix_assets_organization_status", "assets", ["organization_id", "status"], unique=False
    )
    op.create_index(
        "ix_assets_organization_type", "assets", ["organization_id", "asset_type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_assets_organization_type", table_name="assets")
    op.drop_index("ix_assets_organization_status", table_name="assets")
    op.drop_index(op.f("ix_assets_organization_id"), table_name="assets")
    op.drop_index(op.f("ix_assets_ip_address"), table_name="assets")
    op.drop_table("assets")

    sa.Enum(name="asset_discovery_source").drop(
        op.get_bind(),
        checkfirst=True,
    )
    sa.Enum(name="asset_status").drop(
        op.get_bind(),
        checkfirst=True,
    )
    sa.Enum(name="asset_criticality").drop(
        op.get_bind(),
        checkfirst=True,
    )
    sa.Enum(name="asset_environment").drop(
        op.get_bind(),
        checkfirst=True,
    )
    sa.Enum(name="asset_type").drop(
        op.get_bind(),
        checkfirst=True,
    )
    # ### end Alembic commands ###
