"""create vulnerabilities and asset findings

Revision ID: d36799d7534d
Revises: a37be809d87d
Create Date: 2026-08-04 18:45:09.785968

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d36799d7534d"
down_revision: str | Sequence[str] | None = "a37be809d87d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vulnerabilities",
        sa.Column("cve_id", sa.String(length=32), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "severity",
            sa.Enum(
                "critical",
                "high",
                "medium",
                "low",
                "informational",
                "unknown",
                name="vulnerability_severity",
            ),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "manual",
                "nvd",
                "cisa_kev",
                "vendor",
                "nessus",
                "qualys",
                "openvas",
                "aws_inspector",
                "azure_defender",
                "crowdstrike",
                "other",
                name="vulnerability_source",
            ),
            server_default="manual",
            nullable=False,
        ),
        sa.Column("cvss_v2_score", sa.Float(), nullable=True),
        sa.Column("cvss_v2_vector", sa.String(length=255), nullable=True),
        sa.Column("cvss_v3_score", sa.Float(), nullable=True),
        sa.Column("cvss_v3_vector", sa.String(length=255), nullable=True),
        sa.Column("cvss_v4_score", sa.Float(), nullable=True),
        sa.Column("cvss_v4_vector", sa.String(length=255), nullable=True),
        sa.Column("epss_score", sa.Float(), nullable=True),
        sa.Column("epss_percentile", sa.Float(), nullable=True),
        sa.Column("is_cisa_kev", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_patch_available", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "exploit_maturity",
            sa.Enum(
                "none",
                "proof_of_concept",
                "functional",
                "weaponized",
                "unknown",
                name="exploit_maturity",
            ),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column("vendor", sa.String(length=255), nullable=True),
        sa.Column("product", sa.String(length=255), nullable=True),
        sa.Column(
            "affected_versions",
            postgresql.ARRAY(sa.String(length=255)),
            server_default=sa.text("'{}'::character varying[]"),
            nullable=False,
        ),
        sa.Column(
            "cwe_ids",
            postgresql.ARRAY(sa.String(length=32)),
            server_default=sa.text("'{}'::character varying[]"),
            nullable=False,
        ),
        sa.Column(
            "references",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column(
            "metadata_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vulnerabilities")),
    )
    op.create_index(op.f("ix_vulnerabilities_cve_id"), "vulnerabilities", ["cve_id"], unique=True)
    op.create_index(
        op.f("ix_vulnerabilities_cvss_v3_score"), "vulnerabilities", ["cvss_v3_score"], unique=False
    )
    op.create_index(
        op.f("ix_vulnerabilities_epss_score"), "vulnerabilities", ["epss_score"], unique=False
    )
    op.create_index(
        op.f("ix_vulnerabilities_is_cisa_kev"), "vulnerabilities", ["is_cisa_kev"], unique=False
    )
    op.create_index(
        "ix_vulnerabilities_kev_epss",
        "vulnerabilities",
        ["is_cisa_kev", "epss_score"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vulnerabilities_product"), "vulnerabilities", ["product"], unique=False
    )
    op.create_index(
        "ix_vulnerabilities_severity_cvss",
        "vulnerabilities",
        ["severity", "cvss_v3_score"],
        unique=False,
    )
    op.create_index(op.f("ix_vulnerabilities_vendor"), "vulnerabilities", ["vendor"], unique=False)
    op.create_table(
        "asset_vulnerabilities",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("vulnerability_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "in_progress",
                "mitigated",
                "resolved",
                "accepted_risk",
                "false_positive",
                name="vulnerability_status",
            ),
            server_default="open",
            nullable=False,
        ),
        sa.Column(
            "remediation_status",
            sa.Enum(
                "not_started",
                "planned",
                "in_progress",
                "completed",
                "not_applicable",
                name="remediation_status",
            ),
            server_default="not_started",
            nullable=False,
        ),
        sa.Column("scanner_source", sa.String(length=100), server_default="manual", nullable=False),
        sa.Column("scanner_finding_id", sa.String(length=255), nullable=True),
        sa.Column("risk_score", sa.Float(), nullable=True),
        sa.Column("is_exploitable", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("evidence", sa.Text(), nullable=True),
        sa.Column("remediation_recommendation", sa.Text(), nullable=True),
        sa.Column("fixed_version", sa.String(length=255), nullable=True),
        sa.Column(
            "metadata_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_asset_vulnerabilities_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_asset_vulnerabilities_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vulnerability_id"],
            ["vulnerabilities.id"],
            name=op.f("fk_asset_vulnerabilities_vulnerability_id_vulnerabilities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_vulnerabilities")),
        sa.UniqueConstraint(
            "asset_id",
            "vulnerability_id",
            "scanner_source",
            name="uq_asset_vulnerabilities_asset_vulnerability_scanner",
        ),
    )
    op.create_index(
        op.f("ix_asset_vulnerabilities_asset_id"),
        "asset_vulnerabilities",
        ["asset_id"],
        unique=False,
    )
    op.create_index(
        "ix_asset_vulnerabilities_asset_status",
        "asset_vulnerabilities",
        ["asset_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_asset_vulnerabilities_organization_id"),
        "asset_vulnerabilities",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_asset_vulnerabilities_organization_status",
        "asset_vulnerabilities",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_asset_vulnerabilities_risk",
        "asset_vulnerabilities",
        ["organization_id", "risk_score"],
        unique=False,
    )
    op.create_index(
        op.f("ix_asset_vulnerabilities_risk_score"),
        "asset_vulnerabilities",
        ["risk_score"],
        unique=False,
    )
    op.create_index(
        op.f("ix_asset_vulnerabilities_vulnerability_id"),
        "asset_vulnerabilities",
        ["vulnerability_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_asset_vulnerabilities_vulnerability_id"), table_name="asset_vulnerabilities"
    )
    op.drop_index(op.f("ix_asset_vulnerabilities_risk_score"), table_name="asset_vulnerabilities")
    op.drop_index("ix_asset_vulnerabilities_risk", table_name="asset_vulnerabilities")
    op.drop_index(
        "ix_asset_vulnerabilities_organization_status", table_name="asset_vulnerabilities"
    )
    op.drop_index(
        op.f("ix_asset_vulnerabilities_organization_id"), table_name="asset_vulnerabilities"
    )
    op.drop_index("ix_asset_vulnerabilities_asset_status", table_name="asset_vulnerabilities")
    op.drop_index(op.f("ix_asset_vulnerabilities_asset_id"), table_name="asset_vulnerabilities")
    op.drop_table("asset_vulnerabilities")
    op.drop_index(op.f("ix_vulnerabilities_vendor"), table_name="vulnerabilities")
    op.drop_index("ix_vulnerabilities_severity_cvss", table_name="vulnerabilities")
    op.drop_index(op.f("ix_vulnerabilities_product"), table_name="vulnerabilities")
    op.drop_index("ix_vulnerabilities_kev_epss", table_name="vulnerabilities")
    op.drop_index(op.f("ix_vulnerabilities_is_cisa_kev"), table_name="vulnerabilities")
    op.drop_index(op.f("ix_vulnerabilities_epss_score"), table_name="vulnerabilities")
    op.drop_index(op.f("ix_vulnerabilities_cvss_v3_score"), table_name="vulnerabilities")
    op.drop_index(op.f("ix_vulnerabilities_cve_id"), table_name="vulnerabilities")
    op.drop_table("vulnerabilities")

    sa.Enum(name="remediation_status").drop(
        op.get_bind(),
        checkfirst=True,
    )
    sa.Enum(name="vulnerability_status").drop(
        op.get_bind(),
        checkfirst=True,
    )
    sa.Enum(name="exploit_maturity").drop(
        op.get_bind(),
        checkfirst=True,
    )
    sa.Enum(name="vulnerability_source").drop(
        op.get_bind(),
        checkfirst=True,
    )
    sa.Enum(name="vulnerability_severity").drop(
        op.get_bind(),
        checkfirst=True,
    )
    # ### end Alembic commands ###
